name: project3_lab04_nurlisa_52215124595
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0' # Updated to satisfy modern package requirements

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0 # Added for file uploads
  
  # UI & Routing
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  uuid: ^4.5.2
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2 # Added for gallery access

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true